

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: recipe-backend
    container_name: recip-backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: recipe-frontend
    container_name: recip-frontend-container
    ports:
    - "3000:3000"
    - "5173:5173"  # Add this line to expose Vite's default port
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
